import 'product_model.dart';

// بيانات وهمية بصيغة ProductModel
List<ProductModel> dummyProducts = [
  ProductModel(
    id: '1',
    companyId: 'comp_001',
    companyName: 'شركة الأدوية العربية',
    name: 'باراسيتامول',
    concentration: '500mg',
    quantity: 500,
    price: 15.0,
    requiresPrescription: false,
    imageUrl: null,
    expiryDate: DateTime(2025, 12, 31),
    isActive: true,
    createdAt: DateTime.now(),
  ),
  ProductModel(
    id: '2',
    companyId: 'comp_001',
    companyName: 'شركة الأدوية العربية',
    name: 'إيبوبروفين',
    concentration: '400mg',
    quantity: 300,
    price: 20.0,
    requiresPrescription: false,
    imageUrl: null,
    expiryDate: DateTime(2025, 12, 31),
    isActive: true,
    createdAt: DateTime.now(),
  ),
  ProductModel(
    id: '3',
    companyId: 'comp_002',
    companyName: 'شركة النيل للأدوية',
    name: 'أموكسيسيلين',
    concentration: '500mg',
    quantity: 200,
    price: 25.0,
    requiresPrescription: true,
    imageUrl: null,
    expiryDate: DateTime(2025, 10, 31),
    isActive: true,
    createdAt: DateTime.now(),
  ),
  ProductModel(
    id: '4',
    companyId: 'comp_002',
    companyName: 'شركة النيل للأدوية',
    name: 'أزيثروميسين',
    concentration: '250mg',
    quantity: 150,
    price: 35.0,
    requiresPrescription: true,
    imageUrl: null,
    expiryDate: DateTime(2025, 9, 30),
    isActive: true,
    createdAt: DateTime.now(),
  ),
  ProductModel(
    id: '5',
    companyId: 'comp_003',
    companyName: 'شركة الصافي',
    name: 'ديكلوفيناك',
    concentration: '50mg',
    quantity: 400,
    price: 18.0,
    requiresPrescription: true,
    imageUrl: null,
    expiryDate: DateTime(2025, 11, 30),
    isActive: true,
    createdAt: DateTime.now(),
  ),
  ProductModel(
    id: '6',
    companyId: 'comp_003',
    companyName: 'شركة الصافي',
    name: 'فيتامين C',
    concentration: '1000mg',
    quantity: 1000,
    price: 10.0,
    requiresPrescription: false,
    imageUrl: null,
    expiryDate: DateTime(2026, 1, 31),
    isActive: true,
    createdAt: DateTime.now(),
  ),
  ProductModel(
    id: '7',
    companyId: 'comp_004',
    companyName: 'شركة الحياة',
    name: 'فيتامين D3',
    concentration: '5000IU',
    quantity: 600,
    price: 25.0,
    requiresPrescription: false,
    imageUrl: null,
    expiryDate: DateTime(2026, 2, 28),
    isActive: true,
    createdAt: DateTime.now(),
  ),
  ProductModel(
    id: '8',
    companyId: 'comp_002',
    companyName: 'شركة النيل للأدوية',
    name: 'سيتريزين',
    concentration: '10mg',
    quantity: 500,
    price: 18.0,
    requiresPrescription: false,
    imageUrl: null,
    expiryDate: DateTime(2025, 8, 31),
    isActive: true,
    createdAt: DateTime.now(),
  ),
];
